### ISSUE TITLE
Agregar funcionalidad de division

### ISSUE THREAD

**Issue by aralvega** [aralvega/Calculadora#1]
- [x] Crear un método denominado dividir
- [x] Debe recibir 2 parametros que son los números
- [x] Debe dividir los dos números si es válido y devolver el resultado

**Comment by LuxMaximo** [comment]
okey inicio el desarrollo de lo solicitado T-T

**Comment by LuxMaximo** [comment]
Finalizada la tarea con etsito 
@aralvega
